### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(FlightSimContent)
add_subdirectory(Generated)
add_subdirectory(FlightSim)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    FlightSimContentplugin
    Generated_QtQuick3D_Elolapplugin
    Generated_QtQuick3D_Kerekplugin
    Generated_QtQuick3D_Flapplugin
    Generated_QtQuick3D_Flap2plugin
    FlightSimplugin)